# Generated by Django 5.1 on 2024-09-16 03:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_profile_pic_url', max_length=255, null=True, verbose_name='image'),
        ),
    ]
