# Generated by Django 5.1 on 2024-09-16 03:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dqvewferm/image/upload/v1726457813/default_fqcgdm.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
