# Generated by Django 5.1 on 2024-09-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_author_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
                ('story', models.TextField()),
                ('team_member_1_name', models.CharField(max_length=100)),
                ('team_member_1_title', models.CharField(max_length=100)),
                ('team_member_1_image', models.ImageField(upload_to='team_images/')),
                ('team_member_2_name', models.CharField(max_length=100)),
                ('team_member_2_title', models.CharField(max_length=100)),
                ('team_member_2_image', models.ImageField(upload_to='team_images/')),
                ('team_member_3_name', models.CharField(max_length=100)),
                ('team_member_3_title', models.CharField(max_length=100)),
                ('team_member_3_image', models.ImageField(upload_to='team_images/')),
                ('features', models.TextField()),
                ('join_us', models.TextField()),
                ('contact_info', models.TextField()),
            ],
        ),
    ]
