# Generated by Django 5.1 on 2024-09-12 04:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
