# Generated by Django 5.1 on 2024-09-12 07:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_event_image_event_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='team_member_1_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_member_2_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_member_3_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
