# Generated by Django 5.1 on 2024-10-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_posts_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutusPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('who_are_we', models.TextField()),
                ('what_we_do', models.TextField()),
                ('mission', models.TextField()),
                ('vission', models.TextField()),
                ('join_us', models.TextField()),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
